name: C/C++ check

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  check:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: run check
      run: |
        sudo apt-get update >/dev/null && sudo apt-get install -y --no-install-recommends clang-tidy >/dev/null
        make check
